word_dict = {
    'awful' : 'claw-ful',
    'awesome' : 'paw-some',
    'attitude' : 'catitude',
    'feeling' :'feline',
    'friend': 'fur-end',
    'kidding' : 'kitten',
    'lying' : 'lion',
    'me out' : 'meow-t',
    'literally' : 'litter-ally'
}

syllable_dict = {
    'far' : 'fur',
    'fer' : 'fur',
    'fir' : 'fur',
    'for' : 'fur',
    'pon' : 'pawn', 
    'pau': 'paw',
    'pah' : 'paw',
    'par' : 'paw',
    'pros' : 'paws',
    'prop' : 'pawp',
    'pos' : 'paws',
    'hist' : 'hisst',
    'hys' : 'hiss',
    'mu' : 'mew',
    'meo' : 'meow',
    'mo' : 'meow',
    'now' : 'meow',
    'no' : 'nya',
    'pur' : 'purr',
    'pro': 'purr',
    'per' : 'purr',
    'pre' : 'purr',
    'pr' : 'purr',
    'cle' : 'claw', 
}

synonym_dict = {
    'joking' : 'kitten',
    'disaster' : 'cat-astrophe',
    'calamity' : 'cat-astrophe',
    'terrible' : 'claw-ful',
    'horrible' : 'claw-ful',
    'the worst' : 'claw-ful',
    'viable' : 'paw-sible',
    'jerk' : 'sourpuss',
    'sore loser' : 'sourpuss',
    'goof ball' : 'furball',
    'goofball' : 'furball',
    'dork' : 'furball',
    'idiot' : 'paw-looka',
    'basically' : 'pur-actically',
    'hilarious' : 'hiss-terical',
    'insane' : 'hiss-terical',
    'crazy' : 'hiss-terical',
    'funny' : 'hiss-terical',
    'irritated' : 'hissy',
    'angry' : 'hissy',
    'sassy' : 'catty',
    "bee's knees" : "cat's meow",
    "is great" : "is the cat's meow",
    "beautiful" : 'pur-ty',
    'gorgeous' : 'pur-ty',
    'special' : 'pur-ecious'
}
